"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from decouple import config
from importlib.util import find_spec
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

PROJECT_NAME = config('PROJECT_NAME', default="Django REST Framework API", cast=str)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=lambda v: [s.strip() for s in v.split(",")])


# Application definition

INSTALLED_APPS = [
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "rest_framework",
    "drf_standardized_errors",

    "api",
    "database",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "api.urls"

TEMPLATES = [
    {
        'BACKEND': "django.template.backends.django.DjangoTemplates",
        'DIRS': [
            BASE_DIR / "templates",
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Append URL Slash
# https://docs.djangoproject.com/en/5.1/ref/settings/#append-slash

APPEND_SLASH = True


# Django REST Framework
# https://www.django-rest-framework.org/tutorial/quickstart/

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [],
    'UNAUTHENTICATED_USER': None,
    'DEFAULT_PERMISSION_CLASSES': ["rest_framework.permissions.AllowAny"],
    'DEFAULT_RENDERER_CLASSES': ["helpers.response.ResponseRenderer"],
    'EXCEPTION_HANDLER': "drf_standardized_errors.handler.exception_handler",
    'DEFAULT_VERSION': "v1",
}


# DRF Standardized Errors
# https://drf-standardized-errors.readthedocs.io/en/latest/settings.html

DRF_STANDARDIZED_ERRORS = {
    'EXCEPTION_FORMATTER_CLASS': "helpers.exception.StandardExceptionFormatter",
}


# Cache
# https://docs.djangoproject.com/en/5.1/topics/cache/

CACHES = {
    'default': {
        'BACKEND': "django.core.cache.backends.db.DatabaseCache",
        'LOCATION': "django_cache",
        'TIMEOUT': 300,
        'KEY_PREFIX': PROJECT_NAME,
    }
}


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': "django.db.backends.postgresql",
        'NAME': config('DB_NAME', default="postgres", cast=str),
        'USER': config('DB_USER', default="postgres", cast=str),
        'PASSWORD': config('DB_PASS', default="postgres", cast=str),
        'HOST': config('DB_HOST', default="localhost", cast=str),
        'PORT': config('DB_PORT', default=5432, cast=int),
    }
}


# Session
# https://docs.djangoproject.com/en/5.1/topics/http/sessions/

SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"

SESSION_CACHE_ALIAS = "default"

SESSION_COOKIE_AGE = 604800


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {'NAME': "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {'NAME': "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {'NAME': "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

PASSWORD_HASHERS = ["django.contrib.auth.hashers.ScryptPasswordHasher"]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = config('DJANGO_LANGCODE', default="en-us", cast=str)

TIME_ZONE = config('DJANGO_TIMEZONE', default="Asia/Jakarta", cast=str)

USE_I18N = True

USE_TZ = True


# Storage and Media
# https://docs.djangoproject.com/en/5.1/topics/files/

MEDIA_URL = "uploads/"

MEDIA_ROOT = BASE_DIR / "uploads"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Logging
# https://docs.djangoproject.com/en/5.1/topics/logging/

if find_spec('rich'):
    CONSOLE_LOGGER_CLASS = "rich.logging.RichHandler"
else:
    CONSOLE_LOGGER_CLASS = "logging.StreamHandler"

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': "{levelname} {asctime} {module} {message}",
            'style': "{",
        },
        'simple': {
            'format': "{message}",
            'style': "{",
        },
    },
    'handlers': {
        'console': {
            'level': "INFO",
            'class': CONSOLE_LOGGER_CLASS,
            'formatter': "simple",
        },
    },
    'root': {
        'handlers': ["console"],
        'level': "DEBUG",
    },
}


# Testing
# https://docs.djangoproject.com/en/5.1/topics/testing/

TEST_RUNNER = "tests.test_runner.TestRunner"
